"""Generate a gallery of example radiant heating layouts.

Runs the layout engine for a set of realistic rooms, writes an SVG for each
into ``examples/gallery/`` and (re)builds ``examples/README.md`` with a table
and embedded previews. No server required.

    python examples/generate_gallery.py
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from radiantheat import compute_layout  # noqa: E402
from render import render_svg  # noqa: E402

# (name, room_length m, room_width m, pipe_spacing m, note)
ROOMS = [
    ("Bathroom", 3.0, 2.0, 0.15, "Small wet room, tight 150 mm spacing for fast warm-up."),
    ("Bedroom", 5.0, 4.0, 0.20, "Typical bedroom at standard 200 mm spacing."),
    ("Kitchen", 5.0, 3.5, 0.15, "Higher output for a hard-floor kitchen."),
    ("Living room", 8.0, 6.0, 0.20, "Open living space, 200 mm spacing."),
    ("Open-plan floor", 12.0, 9.0, 0.25, "Large open plan, 250 mm spacing."),
    ("Hallway", 8.0, 1.6, 0.15, "Long, narrow corridor."),
    ("Warehouse bay", 30.0, 25.0, 0.30, "Industrial slab (750 m²), static layout."),
]


def slug(name):
    return name.lower().replace(" ", "-").replace("/", "-")


def main():
    gallery = Path(__file__).resolve().parent / "gallery"
    gallery.mkdir(exist_ok=True)

    rows = []
    for name, length, width, spacing, note in ROOMS:
        layout = compute_layout(length, width, spacing)
        svg = render_svg(layout, width_px=520)
        filename = f"{slug(name)}.svg"
        (gallery / filename).write_text(svg, encoding="utf-8")

        cov = layout["coverage"]
        rows.append({
            "name": name,
            "note": note,
            "file": filename,
            "dims": f"{width:g} × {length:g} m",
            "spacing": f"{spacing*1000:g} mm",
            "area": f"{cov['room_area_m2']:g} m²",
            "pipe": f"{layout['pipe_length_m']:g} m",
            "coverage": f"{cov['coverage_percent']:g} %",
            "density": f"{cov['pipe_length_per_m2']:g} m/m²",
        })
        print(f"{name:18s} {rows[-1]['dims']:>12s} @ {rows[-1]['spacing']:>7s} "
              f"-> pipe {rows[-1]['pipe']:>8s}, coverage {rows[-1]['coverage']:>6s}")

    _write_readme(Path(__file__).resolve().parent / "README.md", rows)
    print(f"\nWrote {len(rows)} SVGs to {gallery} and updated examples/README.md")


def _write_readme(path, rows):
    lines = [
        "# Example layouts",
        "",
        "Generated by [`generate_gallery.py`](generate_gallery.py):",
        "",
        "```bash",
        "python examples/generate_gallery.py",
        "```",
        "",
        "| Room | Dimensions | Spacing | Area | Pipe length | Coverage | Density |",
        "| ---- | ---------- | ------- | ---- | ----------- | -------- | ------- |",
    ]
    for r in rows:
        lines.append(
            f"| {r['name']} | {r['dims']} | {r['spacing']} | {r['area']} | "
            f"{r['pipe']} | {r['coverage']} | {r['density']} |"
        )
    lines += ["", "## Previews", ""]
    for r in rows:
        lines += [
            f"### {r['name']}",
            "",
            f"{r['note']}",
            "",
            f"![{r['name']} layout](gallery/{r['file']})",
            "",
        ]
    path.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
